### ISSUE TITLE
Constant Error

### ISSUE THREAD

**Issue by betty02** [mpanighetti/add-securetoken-to-logged-in-user#2]
So bit of background, enrolled my machine in our MDM (Jamf) and then bound to AD. Signed in as the AD user (test) and then ran your script but kept getting the error to retry etc. Wondering how I can troubleshoot?

Basically want it to run on first login to prompt the user for his password so that they can enter it and be enable in securetoken so that I can enable FV for them. I presume I can;t enable FV2 until they are secure right?

]Any help would be hugely appreciated!
Simon

**Comment by WaveBirdDash** [comment]
Can you post the error log from the Jamf policy? Also, did you create an entry for an existing SecureToken user/password in the System keychain and reference that? (replace the `$guiAdmin` string with target username/keychain entry name)

**Comment by betty02** [comment]
Think it maybe something I have done, are you able to assist by dropping me an email at simon[dot]betty[at]gmail[dot]com ? Or betty02 MacAdmins Slack?

Would be hugely appreciated!!

**Comment by betty02** [comment]
User error getting the keychain to work perfectly. I had to scroll through some of the output to find that it was Keychain related as the general error doesn't point me that way. Now that is sorted this works and absolute dream and I am VERR grateful for it!
